const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Plugins.Camera3D,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.windowheight,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchObject
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundo: 0},
	{CartaoFrenteQuadro: 0},
	{CartaCima: 0},
	{CartaAtrás: 0},
	{Mouse: 0},
	{Matriz: 0},
	{Acertos: 0},
	{chances: 0},
	{txtpontos: 0},
	{txtpontosChances: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite: 0},
	{GJogar: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Cronômetro: 0},
	{txt_cronometro: 0},
	{Câmera3D: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Estrelaacertos: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{Áudio: 0},
	{Sprite10: 0},
	{Toque: 0},
	{CartaoMatriz: 0},
	{Espaço1: 0},
	{Cartão1: 0},
	{Espaço2: 0},
	{Cartão2: 0},
	{AtualColuna: 0},
	{AtualLinha: 0},
	{CartaoAtual: 0},
	{GChances: 0},
	{GPartidas: 0},
	{GCartaoResetar: 0},
	{GNumeroCartasEmbaralhar: 0},
	{GMargemTopo: 0},
	{GMargemEsquerda: 0},
	{GEspaçoEntreCartao: 0},
	{GCartaoLargura: 0},
	{GCartaoAltura: 0},
	{GNumerosColunas: 0},
	{GNumerosLinha: 0},
	{GNumeroCartas: 0},
	{GContarCartasEscolhidas: 0},
	{GPrimeiroQuadro: 0},
	{GSegundoQuadro: 0},
	{GReiniciarJogo: 0},
	{GCartasReveladas: 0},
	{GCronometro: 0},
	{GVitoria: 0}
];

self.InstanceType = {
	PlanoDeFundo: class extends self.ITiledBackgroundInstance {},
	CartaAtrás: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Matriz: class extends self.IArrayInstance {},
	Acertos: class extends self.ISpriteInstance {},
	chances: class extends self.ISpriteInstance {},
	txtpontos: class extends self.ITextInstance {},
	txtpontosChances: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	txt_cronometro: class extends self.ITextInstance {},
	Câmera3D: class extends self.IInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Estrelaacertos: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	Áudio: class extends self.IInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {}
}